### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by BlueHorn07** [suzhengpeng/dual-fisheye-video-stitching-in-Python3#1]
When I run this code, I have a problem :(

env) python 3 & anaconda prompt

> (base) C:\Users\dual-fisheye-video-stitching-in-Python3-master>python main.py -o test.mp4 backfront.mp4
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    main(args['input'], args['output'])
  File "main.py", line 95, in main
    M = Hcalc(cap, xmap, ymap)
  File "main.py", line 65, in Hcalc
    templ_shape, maxR)
  File "C:\Users\dual-fisheye-video-stitching-in-Python3-master\feature_matching.py", line 55, in getMatches_goodtemplmatch
    for [[xt, yt]] in kps1:
**TypeError: 'NoneType' object is not iterable**

Please, give me the answer....

**Comment by LogicBypass** [comment]
Hi @BlueHorn07 in "main.py" change "**fourcc = cv2.VideoWriter_fourcc(*'XVID')**" to "**fourcc = cv2.VideoWriter_fourcc(*'mp4v')**"
